[versions]
kotlin = "1.8.21"
jvmToolchain = "17"
paper = "1.19.4-R0.1-SNAPSHOT"

[libraries]
stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

dependencyLoader = { group = "de.md5lukas.paper", name = "paper-dependency-yml", version = "1.0.0-SNAPSHOT" }


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.+" }
runPaper = { id = "xyz.jpenilla.run-paper", version = "2.+" }
spotless = { id = "com.diffplug.spotless", version = "6.+" }